trainer: cifar10
output_dir: $SCRATCH/pytorch-cifar10/output

data_config:
    name: cifar10
    data_path: $SCRATCH/pytorch-cifar10/data
    n_train: 32768 #50000
    n_valid: 8192 #10000
    batch_size: 64

model_config:
    model_type: 'resnet50_cifar10'
    #model_type: 'cnn_classifier'
    #input_shape: [3, 32, 32]
    #conv_sizes: [16, 32, 64]
    #dense_sizes: [128]
    #n_classes: 10
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 1
