trainer: basic
output_dir: $SCRATCH/pytorch-examples/cifar10/output

data:
    name: cifar10
    data_path: $SCRATCH/pytorch-examples/cifar10/data
    n_train: 32768 #50000
    n_valid: 8192 #10000
    batch_size: 64

model:
    name: resnet_cifar10
    #name: cnn
    #input_shape: [3, 32, 32]
    #conv_sizes: [16, 32, 64]
    #fc_sizes: [128]
    #output_size: 10

loss:
    name: CrossEntropyLoss

optimizer:
    name: Adam
    lr: 0.001

metrics:
    acc: Accuracy

train:
    n_epochs: 8
