trainer: basic
output_dir: $SCRATCH/pytorch-mnist/output

data_config:
    name: mnist
    data_path: $SCRATCH/pytorch-mnist/data
    batch_size: 64

model_config:
    model_type: 'cnn_classifier'
    input_shape: [1, 28, 28]
    conv_sizes: [8, 16]
    dense_sizes: [32]
    n_classes: 10
    optimizer: 'Adam'
    learning_rate: 0.001

train_config:
    n_epochs: 1
