trainer: basic
output_dir: $SCRATCH/pytorch-examples/mnist/output

data:
    name: mnist
    data_path: $SCRATCH/pytorch-examples/mnist/data
    batch_size: 64

model:
    name: cnn
    input_shape: [1, 28, 28]
    conv_sizes: [8, 16]
    fc_sizes: [32]
    output_size: 10

loss:
    name: CrossEntropyLoss

optimizer:
    name: Adam
    lr: 0.001

train:
    n_epochs: 1
