trainer: rpvgan
output_dir: $SCRATCH/atlas_gan/RPV_GAN_000

data_config:
    name: rpv_images
    train_file: /global/cscratch1/sd/sfarrell/atlas_gan/data/RPV10_1400_850_01.npz
    n_train: 65536 #262144
    scale: 4.e+6
    batch_size: 64

model_config:
    n_filters: 16
    noise_dim: 64
    optimizer: 'Adam'
    learning_rate: 0.0001
    label_flip_rate: 0.01

train_config:
    n_epochs: 1
